# Generated by Django 6.0.3 on 2026-03-13 23:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                (
                    "deal_type",
                    models.CharField(
                        choices=[
                            ("clearance", "Clearance Sale"),
                            ("financing", "Special Financing"),
                            ("trade_in", "Trade-In Offer"),
                            ("bundle", "Bundle Deal"),
                            ("seasonal", "Seasonal Promotion"),
                            ("new_arrival", "New Arrival"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("short_description", models.CharField(blank=True, max_length=300)),
                (
                    "discount_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("promo_code", models.CharField(blank=True, max_length=50)),
                (
                    "financing_apr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="APR %",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "financing_months",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Term in months", null=True
                    ),
                ),
                (
                    "badge_label",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Save $2,000", "0% APR"',
                        max_length=30,
                    ),
                ),
                (
                    "badge_color",
                    models.CharField(
                        default="#E63946",
                        help_text="Hex color for the badge",
                        max_length=7,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="deals/")),
                ("is_featured", models.BooleanField(default=False)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="deals", to="products.category"
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="deals", to="products.product"
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TradeInRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("make", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("mileage", models.PositiveIntegerField()),
                ("condition_notes", models.TextField(blank=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("zip_code", models.CharField(max_length=10)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("reviewed", "Reviewed"),
                            ("quoted", "Quote Sent"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "offered_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("internal_notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "interested_in",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trade_in_requests",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
    ]
