# Generated by Django 6.0.3 on 2026-04-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="image_url",
            field=models.URLField(blank=True, help_text="Deal image URL"),
        ),
    ]
