# Generated by Django 6.0.3 on 2026-04-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_name_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="model_number",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="short_description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.TextField(unique=True),
        ),
    ]
