# Generated by Django 6.0.3 on 2026-04-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_model_number_alter_product_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="logo_url",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="brand",
            name="website",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="image_url",
            field=models.TextField(
                blank=True, help_text="Category image URL from millermobility.com"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="primary_image_url",
            field=models.TextField(
                blank=True, help_text="Primary image URL from millermobility.com"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="source_url",
            field=models.TextField(
                blank=True, help_text="Product page URL on millermobility.com"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="alt_text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_url",
            field=models.TextField(help_text="Image URL from millermobility.com CDN"),
        ),
    ]
